### PR TITLE
Added TypeScript declaration and test

### PR DESCRIPTION
**Pull request by MikeTschudi**

### CODE REVIEW

**Comment by MikeTschudi** [comment]
@jgravois, second route is fine by me
I can make a separate branch for the first commit--the one that added a test for listDependencies--which is independent of the typings.

**Comment by jgravois** [comment]
awesome!

> I can make a separate branch for the first commit

we could just [🍒-pick](https://git-scm.com/docs/git-cherry-pick) it too.

**Comment by MikeTschudi** [comment]
@jgravois, would you please review the `adlib.d.ts` file in this PR?  If it's OK, I can close this PR and remove the branch after submitting the file to DefinitelyTyped.

I had trouble getting TypeScript to accept both `adlib`'s default returned function `adlib` and its auxiliary function `adlib.listDependencies`.  The latter is in `adlib.d.ts` as a standalone function that has to be called as `adlib.listDependencies` when `adlib` is `require`d (necessary for path change from node_modules) and as `listDependencies` when `adlib` is `import`ed. Seems untidy, but I've been unable to find a better way.

**Comment by jgravois** [comment]
i just did a quick snoop and it looks like there is some goofiness in how adlib is `export`ed that we should fix.

primarily:

> It is bad practice to mix default and named exports in the same module. - [reference](https://rollupjs.org/guide/en#exporting) 

i'll take a crack at that today. i'm hopeful that it'll help with what you're trying to do .

**Comment by jgravois** [comment]
@MikeTschudi since you're going to publish the typings on `@types/` this one is ready to close out now that #33 has landed, correct?

**Comment by MikeTschudi** [comment]
@jgravois--yes, thanks, unless you want to use this PR to track the review of the adlib.d.ts file w/o merging that file into the repo

**Comment by jgravois** [comment]
nah, i trust you. 😉

**Comment by MikeTschudi** [comment]
PR submitted to DefinitelyTyped
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32141

**Comment by MikeTschudi** [comment]
DefinitelyTyped PR merged

**Comment by jgravois** [comment]
_sa_-weet! 🎉

**Pull request closed without merging**
